### ISSUE TITLE
Inventory Bug / Invisible Item.

### ISSUE THREAD

**Issue by BulgaRpl** [VORPCORE/VORP-Inventory#10]
Sometimes when we give something to someone, he doesn't see it in EQ. Only after making a reconnect, this item appears to him.
Even if he has this item, it is not added to the current state, only after reconnect.

**Comment by JaroSound** [comment]
Another problem is, when u give someone a item and his EQ/ItemLimit is full, the item is gone for both, relog wont help in this case.
