### ISSUE TITLE
register a usable item

### ISSUE THREAD

**Issue by JaneEyre12** [VORPCORE/VORP-Inventory#102]
I have figured out how to make the things necessary to be consumable. I can only use consumables and weapons. I have no clue where to input the items to make all other items usable. In the SQL it shows all items as usable. I have tried inputting into inventory config.lua but it throws an error and doesnt allow inventory to load in server. can any one help.

**Comment by outsider31000** [comment]
each script is handling items, if you have items  that are not being used in a script they  wont be used even if its marked as usabled.

most items are not usable they are for crafting or selling. thi isnt an issue, use the discord to get help
