### ISSUE TITLE
fatal error unhandled exception

### ISSUE THREAD

**Issue by blackrof** [VORPCORE/VORP-Inventory#13]
![Capture](https://user-images.githubusercontent.com/43116944/98197556-9a86ad80-1f59-11eb-8787-c68c71875b74.JPG)
how to fix ?

**Comment by rubi216** [comment]
Download ghmattimysql and delete the config file

**Comment by blackrof** [comment]
> Download ghmattimysql and delete the config file

How do  delete the config file

**Comment by rubi216** [comment]
Go to the ghmattimysql file and delete the config

**Comment by Local9** [comment]
I'll add a handler in tomorrow to check the ghmattimysql resource exists, current repo only checks to see if it has started.
