### ISSUE TITLE
Bug Inventory

### ISSUE THREAD

**Issue by Slay3rPT** [VORPCORE/VORP-Inventory#18]
Hello,
Everytime i join a server i get a bug in the inventory. The inventory box and another pop up and don't dissapear. 
Anyone knowns how to fix it?

Thanks
![bug](https://user-images.githubusercontent.com/95575355/144748996-28acc4f3-e4d9-44f0-bee1-040c6e611507.png)

**Comment by creativewild** [comment]
that is not a bug from the vorp inventory, as you see you even have the stable ui open plus another one.
It is very like an issue on your client side.

**Comment by Slay3rPT** [comment]
Thanks for the info. Gonna talk with server host.

**Comment by Slay3rPT** [comment]
Bug fixed!! nui-storage folder..
