### ISSUE TITLE
Inventory_sv.ItemDatabase 

### ISSUE THREAD

**Issue by Riryan** [VORPCORE/VORP-Inventory#2]
after it loads the server side InventoryAPI
it throws the error 
[https://github.com/Riryan/RDX/blob/master/error1.jpg](https://github.com/Riryan/RDX/blob/master/error1.jpg)

**Comment by DevBiiTz** [comment]
> after it loads the server side InventoryAPI
> it throws the error
> https://github.com/Riryan/RDX/blob/master/error1.jpg

you download from releases? redownload last version

**Comment by DevBiiTz** [comment]
https://github.com/VORPCORE/VORP-Inventory/releases/tag/BabyYoda

**Comment by Riryan** [comment]
followed your link, redownloaded still throwing the same error

**Comment by DevBiiTz** [comment]
Artifacts version?

**Comment by DevBiiTz** [comment]
https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/ try 2430 or less 2380

**Comment by DevBiiTz** [comment]
you have installed https://github.com/GHMatti/ghmattimysql/releases

**Comment by DevBiiTz** [comment]
?

**Comment by Riryan** [comment]
trying the older 2380 now, and yes the ghattimysql is installed, and loads at startup

**Comment by DevBiiTz** [comment]
> trying the older 2380 now, and yes the ghattimysql is installed, and loads at startup

can you send a screenshoot from your server.cfg

**Comment by Riryan** [comment]
https://github.com/Riryan/RDX/blob/master/error2.png

**Comment by DevBiiTz** [comment]
you have in localhost?

**Comment by Riryan** [comment]
https://github.com/Riryan/RDX/blob/master/3.png
yes.. I'm gonna try redoin the ghmattimysql. seems thats the only thing left that I can think of

**Comment by DevBiiTz** [comment]
![image](https://user-images.githubusercontent.com/30190276/86268290-dda5ce00-bbbf-11ea-9dc9-e16e0bb88bf4.png)

you need to set ip in this line.
set mysql_connection_string "mysql://root:@localhost/vorp"
if you have password of your database please set the password like this:
set mysql_connection_string "mysql://root:password@localhost/vorp"

**Comment by DevBiiTz** [comment]
and check your ghmattimysql folder if you have a config file delete this
