### ISSUE TITLE
Worked on Windows, SIGABRT on Linux

### ISSUE THREAD

**Issue by eljoncurry2** [VORPCORE/VORP-Inventory#3]
We put in you packages on our windows environment and they worked without an issue.  Super nice and very high quality! Much appreciated!  

We tried to move to Linux (Ubuntu 16.04) tonight and on first run, we get a SIGABRT.  Here is the dump:

`
Creating script environments for vorp_inventory
Symbol file LoadedFromMemory is not a mono symbol file
vorp_inventory: Language en_lang.json loaded!
Instantiated instance of script vorpinventory_sv.Config.
Instantiated instance of script vorpinventory_sv.InventoryAPI.
Instantiated instance of script vorpinventory_sv.ItemDatabase.
Instantiated instance of script vorpinventory_sv.vorpinventory_sv.
Assertion failed: m_marks.empty() (../../../components/citizen-server-impl/src/ResourceFilesComponent.cpp: ~MarkedWriter: 22)
Stacktrace:

/proc/self/maps:
4091d000-40a20000 rwxp 00000000 00:00 0 
4112e000-412c1000 rwxp 00000000 00:00 0 
412da000-412ea000 rwxp 00000000 00:00 0 
412fb000-413de000 rwxp 00000000 00:00 0 
41432000-414f2000 rwxp 00000000 00:00 0 
41c48000-41ce8000 rwxp 00000000 00:00 0 
5fcc3c0000-5fcc400000 rw-p 00000000 00:00 0 
c3c0400000-c3c0440000 rw-p 00000000 00:00 0 
12df5f80000-12df5fc0000 rw-p 00000000 00:00 0 
164cc530000-164cc538000 rw-p 00000000 00:00 0 
18186000000-18186040000 rw-p 00000000 00:00 0 
2b0a80c0000-2b0a8100000 rw-p 00000000 00:00 0 
33de0880000-33de08c0000 rw-p 00000000 00:00 0 
3d270000000-3d270040000 rw-p 00000000 00:00 0 
49ccd8c0000-49ccd900000 rw-p 00000000 00:00 0 
4a34bb40000-4a34bb80000 rw-p 00000000 00:00 0 
5331ac40000-5331ac80000 rw-p 00000000 00:00 0 
5b88dc40000-5b88dc80000 rw-p 00000000 00:00 0 
5c749d80000-5c749dc0000 rw-p 00000000 00:00 0 
65806280000-658062c0000 rw-p 00000000 00:00 0 
6d865a80000-6d865ac0000 rw-p 00000000 00:00 0 
7432fe40000-7432fe80000 rw-p 00000000 00:00 0 
7eb66a40000-7eb66a80000 rw-p 00000000 00:00 0 
86fad8c0000-86fad900000 rw-p 00000000 00:00 0 
95e23e3f000-95e23e40000 ---p 00000000 00:00 0 
Memory around native instruction pointer (0x7f43c41509e2):
0x7f43c41509d2  00 00 b8 0e 00 00 00 31 d2 bf 02 00 00 00 0f 05  .......1........
0x7f43c41509e2  c3 48 63 ff 50 b8 24 00 00 00 0f 05 48 89 c7 e8  .Hc.P.$.....H...
0x7f43c41509f2  ac 9a fd ff 5a c3 48 63 ff 50 48 63 f6 b8 3e 00  ....Z.Hc.PHc..>.
0x7f43c4150a02  00 00 0f 05 48 89 c7 e8 94 9a fd ff 5a c3 85 ff  ....H.......Z...

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
`

If you run the startup again, everything seems fine (no Abort) but inventory or it's systems do not work.  No event trigger for open, buying weapons adds tot he loadout in the database, but again, not accessible through inventory to 'equip'.

**Comment by DevBiiTz** [comment]
We will release a version very soon for linux.
For more information stay on our discord or follow us on this project, sorry for the inconvenience
