### ISSUE TITLE
Error after updating (log attached)

### ISSUE THREAD

**Issue by Xentran94** [VORPCORE/VORP-Inventory#30]
logfile: [CitizenFX_log_2022-01-19T175413.log](https://github.com/VORPCORE/VORP-Inventory/files/7899498/CitizenFX_log_2022-01-19T175413.log)

Hello, after updating to the newst "release" of vorp_inventory the resource stopped working.
The Clientside error occurs at line: 924 in the log above. It directly starts with joining the Server.
Serverside has no errors in console.

Maybe someone can help me.

**Comment by Local9** [comment]
From what I can tell this is due to the Event handling for the config, I'm going to review the process and see what I can do for the client so its not reliant on the speed of someones internet connection.

**Comment by Local9** [comment]
Moving the config to be a file shared by both the server and the client as a file, not sent via an event will fix this, will revisit this after work.
