### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by NiftyLife** [VORPCORE/VORP-Inventory#34]
[    c-scripting-mono] Error: Unhandled exception in Mono script environment: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'charIdentifier'
[    c-scripting-mono]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
[    c-scripting-mono]   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0) [0x00112] in <cf8f429092f345a6bd742c3476e00e06>:0 
[    c-scripting-mono]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
[    c-scripting-mono]   at VorpInventory.Scripts.VorpPlayerInventory.SaveInventoryItemsSupport (CitizenFX.Core.Player player) [0x00309] in <f2822aa5465848288bb4d1df619ecd9a>:0 
[    c-scripting-mono]   at VorpInventory.PluginManager.<AddEvents>b__23_1 (CitizenFX.Core.Player player, System.String reason) [0x000ca] in <f2822aa5465848288bb4d1df619ecd9a>:0 
[    c-scripting-mono]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_1 (System.Object state) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
[    c-scripting-mono]   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0) [0x00112] in <cf8f429092f345a6bd742c3476e00e06>:0 
[    c-scripting-mono]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
[    c-scripting-mono]   at VorpInventory.Scripts.VorpPlayerInventory.SaveInventoryItemsSupport (CitizenFX.Core.Player player) [0x00309] in <f2822aa5465848288bb4d1df619ecd9a>:0 
[    c-scripting-mono]   at VorpInventory.PluginManager.<AddEvents>b__23_1 (CitizenFX.Core.Player player, System.String reason) [0x000ca] in <f2822aa5465848288bb4d1df619ecd9a>:0 
[    c-scripting-mono]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_1 (System.Object state) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00007] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[    c-scripting-mono]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0

**Comment by Local9** [comment]
Should be patched after #36 and all builds since shouldn't cause this error any more in that method.
