### ISSUE TITLE
Error invoking callback for event

### ISSUE THREAD

**Issue by Razzorone** [VORPCORE/VORP-Inventory#41]
I set up a new test server. This message appears in the console when you log in for the first time.

[script:vorp_inventor] Error invoking callback for event vorpCore:getUserWeapons: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'System.Dynamic.ExpandoObject' does not contain a definition for 'charIdentifier'
[script:vorp_inventor]   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,object)
[script:vorp_inventor]   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0) [0x00112] in <cf8f429092f345a6bd742c3476e00e06>:0 
[script:vorp_inventor]   at VorpInventory.Scripts.VorpCoreInvenoryAPI.getUserWeapons (System.Int32 source, CitizenFX.Core.CallbackDelegate function) [0x00119] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInvenoryAPI.cs:448 
[script:vorp_inventor]   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
[script:vorp_inventor]   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]    Exception_EndOfInnerExceptionStack
[script:vorp_inventor]   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00083] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <fbc4ec45371543bfba3678ebb82caf6d>:0 
[script:vorp_inventor]   at CitizenFX.Core.EventHandlerEntry.Invoke (System.String sourceString, System.Object[] args) [0x00064] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\EventHandlerDictionary.cs:107 
[    script:vorp_core] Characters loaded 0

**Comment by Razzorone** [comment]
When I leave the server this message comes up in the console

[script:vorp_inventor] [ERROR] GetCoreUser: Player '1' does not exist.
[script:vorp_inventor] [ERROR] Core didn't return character for player '1', inventory has not been saved.

**Comment by Local9** [comment]
First message should now be handled differently, as for the second one, this is a known issue as the CORE removes all knowledge of the player when they disconnect, in which the Inventory is sometimes behind on seeing this and doesn't get any information back from the CORE. Due to this issue the CORE is the main part of my refactoring over the coming week.
