### ISSUE TITLE
Problems with getItemCount randomly

### ISSUE THREAD

**Issue by Zaickz** [VORPCORE/VORP-Inventory#44]
Havent found out yet why vorpinventory is printing this error.
Maybe u have some ideas
```
Error invoking callback for event vorpCore:getItemCount: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
[script:vorp_inventor]   at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[script:vorp_inventor]   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
[script:vorp_inventor]   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
[script:vorp_inventor]   at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[script:vorp_inventor]   at VorpInventory.Scripts.VorpCoreInvenoryAPI.getItems (System.Int32 source, CitizenFX.Core.CallbackDelegate funcion, System.String item) [0x00035] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInvenoryAPI.cs:580 
[script:vorp_inventor]   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
[script:vorp_inventor]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]    --- End of inner exception stack trace ---
[script:vorp_inventor]   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00051] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Delegate.DynamicInvokeImpl (System.Object[] args) [0x000e7] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.MulticastDelegate.DynamicInvokeImpl (System.Object[] args) [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Delegate.DynamicInvoke (System.Object[] args) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at CitizenFX.Core.EventHandlerEntry.Invoke (System.String sourceString, System.Object[] args) [0x00064] in /src/code/client/clrcore/EventHandlerDictionary.cs:107 
[ citizen-server-impl] server thread hitch warning: timer interval of 319 milliseconds
```

**Comment by Local9** [comment]
try the latest release and let me know if the issue is still occurring.

**Comment by Zaickz** [comment]
[    script:vorp_core] Player Abby dropped (Reason: Game crashed: 0x0).
[    script:vorp_core] Saved player Abby.
[ citizen-server-impl] server thread hitch warning: timer interval of 370 milliseconds
[ citizen-server-impl] server thread hitch warning: timer interval of 221 milliseconds
[script:vorp_inventor] Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object
[script:vorp_inventor]   at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[script:vorp_inventor]   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
[script:vorp_inventor]   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
[script:vorp_inventor]   at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[script:vorp_inventor]   at VorpInventory.Scripts.VorpCoreInventoryAPI.subWeapon (System.Int32 source, System.Int32 weapId) [0x001c7] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInventoryAPI.cs:1018 
[script:vorp_inventor]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <9391d7651e69459eae268d8a1dfa670f>:0 
[script:vorp_inventor]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any] Error: Unhandled exception in Mono script environment: System.NullReferenceException: Object reference not set to an instance of an object
[                 Any]   at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[                 Any]   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
[                 Any]   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
[                 Any]   at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[                 Any]   at VorpInventory.Scripts.VorpCoreInventoryAPI.subWeapon (System.Int32 source, System.Int32 weapId) [0x001c7] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInventoryAPI.cs:1018 
[                 Any]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[                 Any]   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
[                 Any]   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
[                 Any]   at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
[                 Any]   at VorpInventory.Scripts.VorpCoreInventoryAPI.subWeapon (System.Int32 source, System.Int32 weapId) [0x001c7] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInventoryAPI.cs:1018 
[                 Any]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <9391d7651e69459eae268d8a1dfa670f>:0 
[                 Any]   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
Unhandled exception in Mono script environment: System.NullReferenceException: Object reference not set to an instance of an object
  at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
  at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
  at VorpInventory.Scripts.VorpCoreInventoryAPI.subWeapon (System.Int32 source, System.Int32 weapId) [0x001c7] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInventoryAPI.cs:1018 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at CitizenFX.Core.IdentifierCollection+<>c__DisplayClass5_0.<get_Item>b__0 (System.String id) [0x00000] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) [0x0003f] in <621f44bf32b74ec7bfd50971222435b4>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00000] in <621f44bf32b74ec7bfd50971222435b4>:0 
  at CitizenFX.Core.IdentifierCollection.get_Item (System.String type) [0x0000d] in /src/code/client/clrcore/Server/ServerWrappers.cs:139 
  at VorpInventory.Scripts.VorpCoreInventoryAPI.subWeapon (System.Int32 source, System.Int32 weapId) [0x001c7] in L:\ws\fivem\VORP-Inventory\VORP-Inventory[Client-Server]\vorpinventory_sv\Scripts\VorpCoreInventoryAPI.cs:1018 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <9391d7651e69459eae268d8a1dfa670f>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <9391d7651e69459eae268d8a1dfa670f>:0 > quit "Server Restart (Crash erkannt)."

Still a bit buggy. Dont know what happens exactly

**Comment by Local9** [comment]
Oh, I know what happens. *waves angrily at vorp_core*

**Comment by Local9** [comment]
Please try the latest release and let me know if its worse, or has a minor improvement.

**Comment by Zaickz** [comment]
I will close this here and we continue in #48
