### ISSUE TITLE
Inventory don't open and it's too heavy

### ISSUE THREAD

**Issue by Kaique292** [VORPCORE/VORP-Inventory#50]
Change the url of the images, to stop pulling from the vorp_inventory folder and be able to put an external link. For images to load from this link, the image folder is weighing the vorp_inventory too much. The folder is very heavy just for the image, it would be much more interesting to be able to put a URL of a website and to be able to pull the images, it would release that 100MB just of image of the resource and it would improve it a lot!

**Comment by Kaique292** [comment]
Input in config.json, a standard URL pulling inside the image folder, but that allows me to change it to put a URL of a website or VPS to pull these images externally

**Comment by Local9** [comment]
To explain CitizenFX Resources, the resource is compressed and downloaded on connection, so its faster to load images locally off your machine than it is via a weblink.
