### ISSUE TITLE
 No such export vorp_inventoryApi in resource vorp_inventory

### ISSUE THREAD

**Issue by Hamilton199620** [VORPCORE/VORP-Inventory#52]
citizen:/scripting/lua/scheduler.lua:867: No such export vorp_inventoryApi in resource vorp_inventory
this is the error all my scripts are giving me when starting my new server ??

**Comment by Local9** [comment]
this will be related to the Lua files; which should be working as intended;

https://github.com/VORPCORE/VORP-Inventory/blob/master/VORP-Inventory%5BClient-Server%5D/Build/vorp_inventory/vorpInventoryAPI.lua

**Comment by Hamilton199620** [comment]
im still having the same issue

**Comment by Hamilton199620** [comment]
its fixed thank you
