### ISSUE TITLE
Random server crash(s)

### ISSUE THREAD

**Issue by CrownZeroGaming** [VORPCORE/VORP-Inventory#54]
**So the server has randomly been crashing over and over, I reported it to Blue and he said to post the error here on the github and that's the reason for this message.
I provided a screenshot below with the entire error.**

[https://prnt.sc/26npzus](url)

**Comment by Local9** [comment]
This error is related to the vorp adminmenu, not the inventory.

Please open the issue over here: https://github.com/VORPCORE/VORP-AdminMenu
