### ISSUE TITLE
 ghmattimysql-oxmysql 1.9.3

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Inventory#64]
[ script:ghmattimysql] [WARNING] vorp_inventory triggered a deprecated function! Exports from prior to v1.9.0 will be removed in a future update.
[ script:ghmattimysql]       Refer to the readme for information on updating.

**Comment by Local9** [comment]
Would be nice of oxmysql to say what is being deprecated in their messages.

**Comment by outsider31000** [comment]
this is gone
