### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Inventory#68]
[script:vorp_inventor] SCRIPT ERROR in reference call: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
[script:vorp_inventor] Parameter name: index
[script:vorp_inventor] 
[   script:syn_stable] SCRIPT ERROR: error object is not a string
[   script:syn_stable] (nil stack trace)

**Comment by outsider31000** [comment]
will close this cause there's no info whatsoever.
