### ISSUE TITLE
Features Request, Very Helpful for community plugins.

### ISSUE THREAD

**Issue by JaroSound** [VORPCORE/VORP-Inventory#7]
1. Dropping the rest of items when we get over the available limit in EQ. Sometimes it's problematic to set up plugins.
- For example, when we have a wood limit of 20. When we have 15/20 wood and we get 6 at one time, we get nothing. It's nice if it gives 5 and the rest are thrown to the ground or deleted. Same when the whole inventory is full.

2. Whole Inventory Count in Inventory Menu.

**Comment by bozoweed** [comment]
may be add vonfig for this feature can be able and disabled because personnaly i don't want this in my server x)

**Comment by DevBiiTz** [comment]
**It's open source, feel free to edit your own version.**
