### ISSUE TITLE
items not useable for some but are for other and screens locking and items duplicate

### ISSUE THREAD

**Issue by crazyvetfam** [VORPCORE/VORP-Inventory#73]
Inventory crash issues nothing In f8.  Random people can use some items others can't but if the drop it or give it and give back they can use it .   When moving Inventory from   person to any type of storage  the  screens lock some times and some items duplicate
![image](https://user-images.githubusercontent.com/88051046/160302557-4d08d61e-6777-43c0-a7d4-a7cba719c1fe.png)

**Comment by outsider31000** [comment]
@crazyvetfam  This issue does not come from the inventory I tested with VORP stables and works fine. no errors are thrown.

**Comment by outsider31000** [comment]
This is now closed
