### ISSUE TITLE
 items not moving  and duplicating 

### ISSUE THREAD

**Issue by crazyvetfam** [VORPCORE/VORP-Inventory#74]
![image](https://user-images.githubusercontent.com/88051046/160305206-87711520-e362-4663-9521-0d71067d5951.png)

**Comment by outsider31000** [comment]
@crazyvetfam  can you provide a video please

**Comment by crazyvetfam** [comment]
https://user-images.githubusercontent.com/88051046/160311634-fffb829f-314b-4d10-b97d-c52f6d7bd888.mp4

**Comment by outsider31000** [comment]
@crazyvetfam  what's that bar-safe container? that's not from the inventory script I assume it's from the script?

**Comment by outsider31000** [comment]
I have tried to replicate this and i have not gotten the same result. Update the script.

**Comment by outsider31000** [comment]
I have tried to replicate this and i have not gotten the same result. Update the script.
