### ISSUE TITLE
Inventory not re-opening upon relog

### ISSUE THREAD

**Issue by WolfRanger88** [VORPCORE/VORP-Inventory#76]
Inventory does not re-open after relog onto server. No errors in any console shown and no errors in F8 menu.

Series of events

- Join server as new player, create character etc
- run to weapon shop, buy revolver and ammo
- load gun
- holster gun
- walk around etc
- leave server
- relog into server
- select character
- press i once loaded in
- inventory does not open and cursor appears on game screen. Keyboard and mouse no longer work in game as lock out as they would if sat in a menu.

Currently no fix found to resolve. Items still can be purchased and added to inventory but cannot access inventory.

**Comment by outsider31000** [comment]
@WolfRanger88  inventory works fine.  Thats a you problem. Download the premade server files   And try again. 
You probably did something wrong.
