### ISSUE TITLE
Add ".ToUpper()" check when comparing with a weapon hash string

### ISSUE THREAD

**Issue by SimpleSandman** [VORPCORE/VORP-Inventory#83]
Since weapon hashes are all caps (due to them being constants), we need to make sure whatever we're comparing it with needs to be uppercase as well.

Examples of what should be used going forward:
```csharp
if (weaponHash.ToUpper() == "WEAPON_RIFLE_VARMINT") { ... }
if (weaponHash.ToUpper() == someInputString) { ... }
```
--------
Also, some older code is still using a `.Contains()` for comparing a single hash string. Please use `==` going forward.
This was something I cleaned up in the `Config.cs` to enforce uniqueness.

Example to look out for:
```csharp
if ("WEAPON_MELEE_KNIFE_RUSTIC".Contains("WEAPON_MELEE_KNIFE")) 
{ 
    // this will return true because "WEAPON_MELEE_KNIFE_RUSTIC" contains the string "WEAPON_MELEE_KNIFE"
}
```

**Comment by SimpleSandman** [comment]
I love the idea of `GetHashKey()` comparisons, but given we're merely enforcing a key/value relationship with the weapon's hash inside the `Config.json`, we're just looking at two strings and making sure they're exact.

Ideally, all of this would be stored in a database and a PK would be formed around the hash name since that needs to be unique and it would be looked up the most. Sadly, this would be a VORP-wide rework for anything that touches a weapon.

Speaking of uniqueness, I could also look into an error check to see if there are "duplicate" weapon hash names...

**Comment by t3chman** [comment]
Yes, I agree, this would have to be a total re-work and likely a major version change, as pre-existing third-party scripts may not function as expected.

I think you're right that proper string comparisons are the best we can do at this time.

**Comment by outsider31000** [comment]
This issue will be closed now
There are places in discord for discussions, a todo list channel and also a channel to place all the work that will be done to wait for aproval which eventually will be switched to trello.

Lets keep github clean as it's public.
