### ISSUE TITLE
Error syn_society

### ISSUE THREAD

**Issue by RizzooTv** [VORPCORE/VORP-Inventory#88]
https://prnt.sc/urqzRMTM9SV5 

The attempt was to put it in the company store, which is not possible to take out with the v2.0.0 beta either

**Comment by outsider31000** [comment]
try the inventory in the premade to see if it fixes then we will assume its a problem on the newest @RizzooTv

**Comment by Local9** [comment]
Latest build https://github.com/VORPCORE/VORP-Inventory/releases/tag/v2.0.0-beta.3 should have those issues fixed as far as I know.

**Comment by RizzooTv** [comment]
Yes, the premade works wonderfully, that's why I'm reporting it ;)

**Comment by outsider31000** [comment]
try the above then local 9 sent you

**Comment by outsider31000** [comment]
thanks for reporting

**Comment by Local9** [comment]
Test results from beta.2 were as follows; (beta.3 has hideout issue fixed)
![image](https://user-images.githubusercontent.com/6077794/163607508-ca1a99ff-cf5f-4fd3-8259-13c5cbd2d8e0.png)

**Comment by RizzooTv** [comment]
also with beta3 the same error at syn_society https://prnt.sc/ZAwZZ8F7aWLv

**Comment by Local9** [comment]
ok, I'll poke about and see if its the same issue as hideouts

**Comment by Local9** [comment]
Is there more information around this error other than what the SQL is outputting as that will help knowing which event or line is being called.

**Comment by RizzooTv** [comment]
Unfortunately no, there is nothing in the f8 console, there is only this error, when you try to remove something, it does NOT happen, it just doesn't work, and when you put it in, the error comes.

**Comment by Local9** [comment]
The error would be in the server, I'd doubt you'll see anything on the client without enabling errors in the fxmanifest

**Comment by Local9** [comment]
[patch-inventory-ui.zip](https://github.com/VORPCORE/VORP-Inventory/files/8497561/patch-inventory-ui.zip)

**Comment by Local9** [comment]
Updates have also been done to the beta.3 build files; https://github.com/VORPCORE/VORP-Inventory/releases/tag/v2.0.0-beta.3

**Comment by RizzooTv** [comment]
It works now, thank you <3
