### ISSUE TITLE
Unable to reload ammo

### ISSUE THREAD

**Issue by DerHobbs** [VORPCORE/VORP-Inventory#96]
Since the last update today, you can no longer reload, the ammunition is not displayed, you only have the ammo after a relog

https://streamable.com/020egg

**Comment by Local9** [comment]
I believe I know what this is connected with.

**Comment by Local9** [comment]
Welcome to try these attached files;
[VORP.Inventory.zip](https://github.com/VORPCORE/VORP-Inventory/files/8544813/VORP.Inventory.zip)

**Comment by DerHobbs** [comment]
Now it works again, wonderful THANK YOU
